Add '+' char to IssueId validation
RedHatInsights/insights-remediations pull request #6
Opened 2021-02-03 11:47 UTC by jiridostal

'+' is a valid character to be contained in package names and versions. 
Some examples:
Package name: 'libstdc++'
Package with module: qemu-guest-agent-15:4.2.0-34.module+el8.3.0+8829+e7a0a3ea.1.x86_64

Currently, remediation fails on API validation due to this.

2021-02-09 15:51 UTC, jiridostal commented
@aleccohan could you please have a look? It does not allow Patch to select all packages on the system (which will most likely contain a package with '+' in it) and remediate it.

2021-02-09 19:33 UTC, aleccohan requested changes
@jiridostal 2 quick things.

1. Wrt the placement of this regex pattern this is not actually the place where the issue_id is checked.  We do that here --> https://github.com/RedHatInsights/insights-remediations/blob/master/src/util/identifiers.js#L4.  Additionally would you be able to add some unit tests for issues that look like that in here --> https://github.com/RedHatInsights/insights-remediations/blob/master/src/util/identifiers.unit.js?

2.  Did you re-clone this repo before pushing this commit?  I just recently shifted Insights-remediation to be a public repo and as such I had to scrub the commit history.  Just want to make sure that none of the old changes get pushed back up!

2021-02-10 12:34 UTC, jiridostal commented
1. Fixed the other place and added test cases for Patch
2. I've rebased these two commits on top of this repo, so that shouldn't be a problem.

2021-02-10 13:35 UTC, aleccohan requested changes
Hey Jiri!  So those changes are looking good now.  However I think that (based on the format of some of these issues) the PKG_PATTERN regex defined --> https://github.com/RedHatInsights/insights-remediations/blob/master/src/issues/index.js#L10 will also fail for issues of this format.  

Additionally, this PKG_PATTERN is used in the default package templates stored in remediations as input sanitation.  Could you update the Pattern here as well? 
https://github.com/RedHatInsights/insights-remediations/blob/master/src/templates/static/patchman/packages.yml

2021-02-10 16:22 UTC, Josca commented
@aleccohan thanks, I've updated PKG_PATTERN regex and added some tests. It should be fixed now.

2021-02-10 16:28 UTC, aleccohan commented
@Josca Thanks!  This looks great.  Just one more quick thing before it is merged.  Would you be able to update the package regex in the default package template to match the updated package regex?
i.e.  https://github.com/RedHatInsights/insights-remediations/blob/master/src/templates/static/patchman/packages.yml#L9

Once that's in then I'll go ahead and approve it!

2021-02-10 16:58 UTC, Josca commented
@aleccohan sure, I've just did it in separate PR as this is @jiridostal 's one.

2021-02-11 22:38 UTC, Josca commented
@jiridostal you can close that. Updates were merged in #10 .

2021-02-12 08:01 UTC, closed without merging